import argparse
import ast
import base64
import binascii
import hashlib
import inspect
import json
import re
import subprocess
import sys
from pathlib import Path

import sqlglot
from app.main import app
from app.observability import ObservedRoute
from fastapi.routing import APIRoute, iter_route_contexts
from sqlglot import exp

try:
    from tools.api_design import detail_design, message_design, query_design, unit_factors
    from tools.api_sequence import (
        response_cases,
        routing_cases,
        schema_name,
        sequence,
        verify_framework,
    )
    from tools.generate_queries import check_architecture, collect
    from tools.infra_design import infrastructure_docs
    from tools.requirements_view import derive
    from tools.test_catalog import collect_tests
except ModuleNotFoundError:
    from api_design import detail_design, message_design, query_design, unit_factors
    from api_sequence import response_cases, routing_cases, schema_name, sequence, verify_framework
    from generate_queries import check_architecture, collect
    from infra_design import infrastructure_docs
    from requirements_view import derive
    from test_catalog import collect_tests

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs/generated"
BANNER = "<!-- Generated by tools/design.py. Do not edit. -->\n\n"
SOURCE_URL = "https://github.com/tsuji-tomonori/CornellNoteWebv2/blob/dev/"


def cell(value) -> str:
    def raw(item):
        if isinstance(item, dict):
            return "; ".join(f"{k}: {raw(v)}" for k, v in sorted(item.items()))
        if isinstance(item, list):
            return ", ".join(raw(v) for v in item)
        return str(item)

    return (
        raw(value)
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "\\|")
        .replace("\n", "<br>")
    )


def suppression_reason(value):
    try:
        return base64.b64decode(value, validate=True).decode("utf-8")
    except (binascii.Error, UnicodeDecodeError):
        return value


def table(headers, rows) -> str:
    rows = list(rows)
    if not rows:
        return "該当なし。\n\n"
    return (
        "| "
        + " | ".join(headers)
        + " |\n| "
        + " | ".join("---" for _ in headers)
        + " |\n"
        + "".join("| " + " | ".join(cell(v) for v in row) + " |\n" for row in rows)
        + "\n"
    )


def source(path, line=None) -> str:
    name = str(path.relative_to(ROOT)) if isinstance(path, Path) else path
    return f"[{name}{':' + str(line) if line else ''}]({SOURCE_URL}{name}{'#L' + str(line) if line else ''})"


def page(title, body) -> str:
    return f"# {title}\n\n{BANNER}{body.rstrip()}\n"


def fields(schema, schemas, prefix="$", required=True, seen=()) -> list:
    if "$ref" in schema:
        name = schema["$ref"].split("/")[-1]
        if name in seen:
            return [(prefix, name, required, "再帰参照", "")]
        return fields(schemas[name], schemas, prefix, required, (*seen, name))
    kind = schema.get("type", "union" if "anyOf" in schema else "object")
    constraints = {
        k: v
        for k, v in schema.items()
        if k not in {"properties", "items", "anyOf", "required", "type", "title", "description"}
    }
    rows = [
        (prefix, kind, "必須" if required else "省略可", schema.get("description", ""), constraints)
    ]
    for name, value in schema.get("properties", {}).items():
        rows += fields(
            value, schemas, prefix + "." + name, name in schema.get("required", []), seen
        )
    if "items" in schema:
        rows += fields(schema["items"], schemas, prefix + "[]", False, seen)
    for i, value in enumerate(schema.get("anyOf", []), 1):
        rows += fields(value, schemas, f"{prefix} (候補{i})", required, seen)
    return rows


def function_at(path, name):
    tree = ast.parse(path.read_text())
    return next(n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == name)


def errors(node, path):
    result = []
    for n in ast.walk(node):
        if isinstance(n, ast.Call) and ast.unparse(n.func) == "HTTPException":
            values = dict(zip(["status_code", "detail"], n.args, strict=False))
            values.update({k.arg: k.value for k in n.keywords})
            result.append(
                (
                    ast.literal_eval(values["status_code"]),
                    ast.literal_eval(values["detail"]),
                    source(path, n.lineno),
                )
            )
    return sorted(result)


def database_docs(queries):
    statements = []
    for path in sorted((ROOT / "backend/migrations").glob("*.sql")):
        statements += [(path, n) for n in sqlglot.parse(path.read_text(), dialect="postgres") if n]
    path = ROOT / "backend/src/app/migrate.py"
    for node in ast.walk(ast.parse(path.read_text())):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "execute"
            and node.args
        ):
            literal = node.args[0]
            if (
                isinstance(literal, ast.Constant)
                and isinstance(literal.value, str)
                and literal.value.startswith(("CREATE TABLE", "COMMENT ON"))
            ):
                statements += [(path, sqlglot.parse_one(literal.value, dialect="postgres"))]
    comments = {}
    tables = {}
    indexes = []
    for path, statement in statements:
        if isinstance(statement, exp.Comment):
            comments[statement.this.sql(dialect="postgres")] = statement.expression.this
        elif isinstance(statement, exp.Create) and statement.kind == "TABLE":
            tables[statement.this.this.name] = (path, statement)
        elif isinstance(statement, exp.Create) and statement.kind == "INDEX":
            indexes.append((path, statement))
        else:
            raise ValueError("Unsupported DDL; extend extractor: " + statement.sql())
    files = {}
    er = ["erDiagram"]
    for name, (path, statement) in sorted(tables.items()):
        if name not in comments:
            raise ValueError("Missing Japanese table comment: " + name)
        columns = []
        er.append(f"    {name} {{")
        for c in statement.this.expressions:
            if not isinstance(c, exp.ColumnDef):
                raise ValueError("Unsupported table constraint: " + c.sql())
            description = comments.get(name + "." + c.name)
            if not description:
                raise ValueError("Missing column comment: " + name + "." + c.name)
            kinds = [constraint.kind for constraint in c.constraints]
            if any(isinstance(k, exp.Reference) for k in kinds):
                raise ValueError("Foreign key requires ER extraction support")
            pk = any(isinstance(k, exp.PrimaryKeyColumnConstraint) for k in kinds)
            nonnull = pk or any(isinstance(k, exp.NotNullColumnConstraint) for k in kinds)
            columns.append(
                (
                    c.name,
                    c.kind.sql(dialect="postgres"),
                    "不可" if nonnull else "可",
                    "PK" if pk else "",
                    ", ".join(k.sql(dialect="postgres") for k in kinds),
                    description,
                )
            )
            er.append(
                f'        {c.kind.sql(dialect="postgres").replace("(", "_").replace(")", "")} {c.name}{" PK" if pk else ""} "{description}"'
            )
        er.append("    }")
        relevant = [q for q in queries if q["table"] == name]
        body = (
            comments[name]
            + "\n\n正本: "
            + source(path)
            + "\n\n## カラム\n\n"
            + table(["カラム", "型", "NULL", "キー", "制約・既定値", "日本語説明"], columns)
        )
        body += "## インデックス\n\n" + table(
            ["名前", "定義", "正本"],
            (
                (n.this.name, n.sql(dialect="postgres"), source(p))
                for p, n in indexes
                if n.this.args["table"].name == name
            ),
        )
        body += "## API・SQLによる操作\n\n" + table(
            ["API", "CRUD", "SQL"],
            ((q["api"], q["operation"], source(q["source"])) for q in relevant),
        )
        body += "## DDL\n\n```sql\n" + statement.sql(dialect="postgres", pretty=True) + ";\n```\n"
        files[f"database/tables/{name}.gen.md"] = page(name + " テーブル仕様", body)
    files["database/er.gen.md"] = page(
        "DB全体ER図",
        "DDLに定義された物理テーブルを表示する。現在、外部キーは定義されていないため関連線はない。owner_idは外部認証主体でありDB外部キーではない。\n\n```mermaid\n"
        + "\n".join(er)
        + "\n```",
    )
    operations = {"INSERT": "C", "SELECT": "R", "UPDATE": "U", "DELETE": "D"}
    names = sorted(tables)
    apis = sorted({q["api"] for q in queries})
    matrix = [
        (
            api,
            *[
                " / ".join(
                    sorted(
                        {
                            operations[q["operation"]]
                            for q in queries
                            if q["api"] == api and q["table"] == name
                        }
                    )
                )
                or "—"
                for name in names
            ],
        )
        for api in apis
    ]
    diagrams = ""
    for name in names:
        for operation, code in operations.items():
            relevant = sorted(
                {q["api"] for q in queries if q["table"] == name and q["operation"] == operation}
            )
            if relevant:
                diagram = 'flowchart TD\n  DB["' + name + '"]'
                for i, api in enumerate(relevant):
                    diagram += f'\n  A{i}["{api}"] -->|{code}| DB'
                diagrams += f"## {name} {operation}\n\n```mermaid\n{diagram}\n```\n\n"
    files["database/crud.gen.md"] = page(
        "テーブル × API CRUD図",
        "C=作成 / R=参照 / U=更新 / D=削除。SQL文種別に基づく対応で、UPDATE・DELETEのWHERE判定は別のRとして加算しない。schema_migrationsはAPIから直接操作せずmigrationで管理する。\n\n"
        + table(["API", *names], matrix)
        + diagrams
        + "## SQL・カラム詳細\n\n"
        + table(
            ["テーブル", "API", "SQL操作", "参照列", "書込列", "正本"], (crud(q) for q in queries)
        ),
    )
    files["database/migrations.gen.md"] = page(
        "マイグレーション仕様",
        "適用処理: "
        + source("backend/src/app/migrate.py")
        + "\n\n"
        + table(
            ["ファイル", "SHA-256", "DDL"],
            (
                (source(p), hashlib.sha256(p.read_bytes()).hexdigest(), p.read_text())
                for p in sorted((ROOT / "backend/migrations").glob("*.sql"))
            ),
        ),
    )
    files["database/index.gen.md"] = page(
        "DB一覧",
        table(
            ["テーブル", "仕様", "説明"],
            ((n, f"[仕様](tables/{n}.gen.md)", comments[n]) for n in sorted(tables)),
        )
        + "\n[ER図](er.gen.md) · [CRUD](crud.gen.md) · [マイグレーション](migrations.gen.md)\n",
    )
    return files


def crud(q):
    n = sqlglot.parse_one((ROOT / q["source"]).read_text(), dialect="postgres")
    read = sorted({c.name for c in n.find_all(exp.Column)})
    write = []
    if isinstance(n, exp.Insert):
        write = [c.name for c in n.this.expressions]
    if isinstance(n, exp.Update):
        write = [c.this.name for c in n.expressions]
    return q["table"], q["api"], q["operation"], read, write, source(q["source"])


def api_docs(queries, catalog):
    verify_framework(app)
    spec = app.openapi()
    schemas = spec.get("components", {}).get("schemas", {})
    routes = [r for r in iter_route_contexts(app.routes) if isinstance(r.original_route, APIRoute)]
    definitions = [
        (p, m.upper(), d)
        for p, methods in sorted(spec["paths"].items())
        for m, d in sorted(methods.items())
        if m in {"get", "put", "post", "delete", "patch", "head", "options"}
    ]
    if len(definitions) != len(routes) or len({d["operationId"] for _, _, d in definitions}) != len(
        definitions
    ):
        raise ValueError("OpenAPI/route cardinality or operation ID conflict")
    files, overview = {}, []
    for path, method, d in definitions:
        matching = [
            r
            for r in routes
            if r.operation_id == d["operationId"] and r.path == path and method in r.methods
        ]
        if len(matching) != 1:
            raise ValueError("OpenAPI and effective route must be one-to-one")
        route = matching[0]
        if not isinstance(route.original_route, ObservedRoute):
            raise ValueError("Log catalog requires ObservedRoute: " + d["operationId"])
        op = d["operationId"]
        handler_path = Path(inspect.getfile(route.endpoint))
        handler = function_at(handler_path, route.endpoint.__name__)
        function_path = handler_path.parent / "functions.py"
        if function_path.exists():
            function = function_at(function_path, "execute")
        elif op == "local_login":
            function_path = ROOT / "backend/src/app/auth.py"
            function = function_at(function_path, "local_login")
        else:
            function_path, function = handler_path, handler
        authenticated = bool(d.get("security"))
        reqs = [
            r
            for r in catalog["requirements"]
            if str(function_path.relative_to(ROOT)) in r["traces"]["implementation"]
            or str(handler_path.relative_to(ROOT)) in r["traces"]["implementation"]
        ]
        qs = [q for q in queries if q["api"] == handler_path.parent.name]
        err = errors(function, function_path)
        auth_err = []
        if authenticated:
            auth_path = ROOT / "backend/src/app/auth.py"
            auth_err = errors(function_at(auth_path, "authenticate"), auth_path)
            err += auth_err
        base = f"apis/{op}/"
        intro = f"`{method} {path}` / operationId: `{op}`\n\nハンドラ: {source(handler_path, handler.lineno)}\n\n処理: {source(function_path, function.lineno)}\n\n"
        overview.append(
            (
                op,
                method,
                path,
                "Bearer JWT" if authenticated else "なし（local_loginはlocalモードのみ）",
                f"[{op}]({op}/if.gen.md)",
            )
        )
        params = d.get("parameters", [])
        expected_path = set(re.findall(r"\{([^}]+)\}", path))
        if expected_path != {p["name"] for p in params if p["in"] == "path" and p.get("required")}:
            raise ValueError("Path parameter mismatch: " + op)
        body = (
            intro
            + "## 認証\n\n"
            + (
                "Bearer JWT。Depends(authenticate)でCognitoまたはローカルJWTを検証する。\n\n"
                if authenticated
                else "OpenAPI上の認証依存なし。実装中のモード制限・入力判定はmessagesを参照。\n\n"
            )
        )
        for location, title in [
            ("header", "Headers"),
            ("path", "Path Parameters"),
            ("query", "Query Parameters"),
        ]:
            selected_params = [p for p in params if p["in"] == location]
            rows = [
                (
                    p["name"],
                    schema_name(p["schema"]),
                    p.get("required", False),
                    p.get("description", ""),
                    p["schema"],
                )
                for p in selected_params
            ]
            if location == "header" and authenticated:
                rows.append(
                    (
                        "Authorization",
                        "Bearer JWT",
                        True,
                        "本人のCognitoまたはローカルJWT",
                        "署名・有効期限・subを検証する",
                    )
                )
            body += f"## {title}\n\n" + table(["項目", "型", "必須", "説明", "制約"], rows)
        for media, content in d.get("requestBody", {}).get("content", {}).items():
            body += (
                "## Data / Request "
                + media
                + "\n\n"
                + table(["項目", "型", "必須", "説明", "制約"], fields(content["schema"], schemas))
            )
        for status, response in sorted(d["responses"].items()):
            body += f"## Response {status}\n\n{response['description']}\n\n"
            for media, content in response.get("content", {}).items():
                body += (
                    media
                    + "\n\n"
                    + table(
                        ["項目", "型", "必須", "説明", "制約"],
                        fields(content.get("schema", {}), schemas),
                    )
                )
        body += "## 実装から抽出した追加エラー\n\n" + table(
            ["HTTP", "detail（文字列）", "発生箇所"], sorted(set(err))
        )
        files[base + "if.gen.md"] = page(op + " IF仕様", body)
        response_table = table(["HTTP", "処理区分", "条件", "応答内容"], response_cases(d, err))
        common_table = table(
            ["HTTP", "処理区分", "条件", "応答内容"], routing_cases(app.router.redirect_slashes)
        )
        incoming = [
            (p["in"], p["name"], schema_name(p["schema"]), p.get("required", False)) for p in params
        ]
        if authenticated:
            incoming.append(("header", "Authorization", "Bearer JWT", True))
        incoming += [
            ("body", media, schema_name(c["schema"]), d["requestBody"].get("required", False))
            for media, c in d.get("requestBody", {}).get("content", {}).items()
        ]
        access = []
        for q in qs:
            sql = sqlglot.parse_one((ROOT / q["source"]).read_text(), dialect="postgres")
            where = sql.args.get("where")
            access.append(
                (
                    q["table"],
                    q["operation"],
                    q["summary"],
                    where.sql(dialect="postgres") if where else "なし",
                    list(q["params"]),
                )
            )
        files[base + "sequence.gen.md"] = page(
            op + " シーケンス",
            intro
            + "## 入力\n\n"
            + table(["位置", "名前", "型", "必須"], incoming)
            + "## 呼出し・分岐・応答\n\n"
            + "生成ラッパー・with・変換用関数の表示を省き、ifとtry/catch、DB操作、HTTP応答を表示する。breakはその経路の終了。入力と認証に複数の不備がある場合の検証順序は省略し、確定した応答別に分岐する。\n\n"
            + sequence(function, qs, request=f"{method} {path}", definition=d, auth_errors=auth_err)
            + "\n## DBアクセス\n\n"
            + table(["テーブル", "操作", "処理", "絞込み条件", "バインド引数"], access)
            + (
                "接続は`DSQL_HOST`（AWSのAurora DSQL）または`DATABASE_URL`（ローカルPostgreSQL）。接続処理: "
                + source("backend/src/app/db.py")
                + " / ローカル構成: "
                + source("compose.yaml")
                + "\n\n"
                if qs
                else "このAPIはDBへアクセスしない。\n\n"
            )
            + "## このAPIのHTTP応答\n\n"
            + response_table
            + "## ハンドラ到達前の共通応答\n\n"
            + common_table
            + "共通404はURL不一致であり、一覧が空であることを意味しない。500は未処理例外の標準応答であり、DB失敗が必ず500とは限らない（更新競合の409などは個別catchを優先する）。\n\n"
            + "根拠: 実装AST・OpenAPI・現在の標準例外ハンドラ。共通応答の実測テスト: "
            + source("backend/tests/test_response_contract.py")
            + "。CloudFront/API Gateway自身のエラーはこのFastAPI図の対象外。\n",
        )
        body += "## 共通処理を含む応答一覧\n\n" + response_table + common_table
        files[base + "if.gen.md"] = page(op + " IF仕様", body)
        detail = intro + detail_design(
            root=ROOT,
            function=function,
            definition=d,
            queries=qs,
            incoming=incoming,
            responses=response_cases(d, err),
            fields=fields,
            schemas=schemas,
            table=table,
        )
        detail += "## 5. 要件との直接対応\n\n" + table(
            ["要件", "タイトル"], ((r["id"], r["title"]) for r in reqs)
        )
        files[base + "detail-design.gen.md"] = page(op + " 詳細設計", detail)
        files[base + "messages.gen.md"] = page(
            op + " ログ・メッセージ台帳",
            intro + message_design(op, response_cases(d, err), table, source),
        )
        files[base + "query.gen.md"] = page(
            op + " SQL仕様", intro + query_design(ROOT, qs, table, source)
        )
        factors = intro + unit_factors(function, response_cases(d, err), table)
        factors += "## 入力スキーマの制約\n\n" + table(
            ["場所", "スキーマ"],
            [("parameters", params), ("requestBody", d.get("requestBody", {}))],
        )
        factors += "## 要件の受入基準\n\n" + table(
            ["要件", "Given", "When", "Then", "検証ソース（ファイル単位）"],
            (
                (
                    r["id"],
                    ac["given"],
                    ac["when"],
                    ac["then"],
                    [source(t) for t in r["traces"]["tests"]],
                )
                for r in reqs
                for ac in r["acceptance_criteria"]
            ),
        )
        files[base + "unit-test.gen.md"] = page(op + " テスト観点", factors)
    files["apis/index.gen.md"] = page(
        "API一覧",
        table(["Operation", "Method", "Path", "認証", "IF仕様"], overview)
        + "各APIにIF・詳細設計・シーケンス・メッセージ・SQL・テスト観点の6文書を生成する。\n",
    )
    return files


def additional_docs(catalog):
    files = {
        "requirements/index.gen.md": page(
            "要件仕様一覧",
            "正本: "
            + source("spec/requirements/requirements.qnt")
            + f"\n\nカタログ版: {catalog['catalog_revision']} / 製品: {catalog['product']}\n\nQuintの型・不変条件・traceを検証し、メモリ上で直列化したJSONから生成する。\n\n"
            + table(
                ["要件", "タイトル", "状態", "種別"],
                (
                    (f"[{r['id']}]({r['id']}.gen.md)", r["title"], r["status"], r["category"])
                    for r in catalog["requirements"]
                ),
            ),
        )
    }
    for r in catalog["requirements"]:
        body = table(
            ["項目", "仕様"],
            ((k, v) for k, v in r.items() if k not in {"acceptance_criteria", "traces"}),
        )
        body += "## 受入基準\n\n" + table(
            ["ID", "Given", "When", "Then"],
            ((a["id"], a["given"], a["when"], a["then"]) for a in r["acceptance_criteria"]),
        )
        body += "## トレーサビリティ\n\n" + table(
            ["種類", "正本の参照"], ((k, [source(p) for p in v]) for k, v in r["traces"].items())
        )
        files[f"requirements/{r['id']}.gen.md"] = page(r["id"] + " " + r["title"], body)
    files["requirements/trace.gen.md"] = page(
        "要件対応表",
        table(
            ["要件", "状態", "設計", "実装", "テスト"],
            (
                (
                    r["id"],
                    r["status"],
                    [source(p) for p in r["traces"]["design"]],
                    [source(p) for p in r["traces"]["implementation"]],
                    [source(p) for p in r["traces"]["tests"]],
                )
                for r in catalog["requirements"]
            ),
        ),
    )
    frontend = json.loads(
        subprocess.check_output(["node", "tools/frontend_design.mjs"], cwd=ROOT, text=True)
    )
    for item in frontend["files"]:
        files["frontend/" + Path(item["path"]).stem + ".gen.md"] = page(
            item["path"] + " 画面・型・関数",
            "正本: "
            + source(item["path"])
            + "\n\n## Imports\n\n"
            + table(["依存"], ((x,) for x in item["imports"]))
            + "## 型・インターフェース\n\n"
            + table(["宣言"], ((x,) for x in item["types"]))
            + "## 関数\n\n"
            + table(
                ["名前", "引数", "戻り値", "行"],
                (
                    (f["name"], f["parameters"], f["returnType"], f["line"])
                    for f in item["functions"]
                ),
            )
            + "## JSX属性\n\n"
            + table(["属性", "値"], ((v["attribute"], v["value"]) for v in item["ui"]))
            + "静的ASTの範囲。画面の配置・見た目はE2Eレポートのスクリーンショットで検証する。\n",
        )
    files["tests/e2e.gen.md"] = page(
        "Playwrightシナリオ",
        table(
            ["ケース", "段階", "日本語の操作・期待結果"],
            (
                (case["title"], step["kind"], step["text"])
                for case in frontend["cases"]
                for step in case["steps"]
            ),
        )
        + "実行成否とスクリーンショット: [品質レポート](https://tsuji-tomonori.github.io/CornellNoteWebv2/)\n",
    )
    tests = []
    for p in sorted(
        [
            *ROOT.glob("backend/tests/test_*.py"),
            *ROOT.glob("infra/tests/test_*.py"),
            *ROOT.glob("tests/test_*.py"),
        ]
    ):
        for n in ast.parse(p.read_text()).body:
            if isinstance(n, ast.FunctionDef) and n.name.startswith("test_"):
                tests.append(
                    (
                        source(p, n.lineno),
                        n.name,
                        [ast.unparse(c.test) for c in ast.walk(n) if isinstance(c, ast.Assert)],
                    )
                )
    files["tests/pytest.gen.md"] = page(
        "pytestテストと検証式",
        table(["正本", "テスト関数", "assert"], tests)
        + "AST上のテスト定義。parametrizeの実行件数や成否はCIレポートを参照する。\n",
    )
    template = json.loads((ROOT / "cdk.out/CornellNote.template.json").read_text())
    resources = template["Resources"]
    for r in resources.values():
        if r["Type"] == "AWS::Lambda::Function":
            r["Properties"]["Code"] = {"Artifact": "uv.lock runtime bundle"}
    files["infrastructure/resources.gen.md"] = page(
        "AWSリソース仕様",
        table(
            ["Logical ID", "Type", "Properties"],
            ((k, v["Type"], v.get("Properties", {})) for k, v in sorted(resources.items())),
        )
        + "Lambdaのビルド成果物S3キーは環境差を除くため正規化する。コードとuv.lockはmanifestで別途ハッシュ化する。\n",
    )
    files["infrastructure/iam.gen.md"] = page(
        "IAM・リソースポリシー",
        table(
            ["Logical ID", "Type", "ポリシー・信頼関係"],
            (
                (k, v["Type"], v["Properties"])
                for k, v in sorted(resources.items())
                if "Policy" in v["Type"] or v["Type"] == "AWS::IAM::Role"
            ),
        ),
    )
    files["infrastructure/nag.gen.md"] = page(
        "cdk-nag抑制理由",
        table(
            ["Logical ID", "抑制ID", "理由", "適用対象"],
            (
                (k, s["id"], suppression_reason(s["reason"]), s.get("appliesTo", []))
                for k, v in sorted(resources.items())
                for s in v.get("Metadata", {}).get("cdk_nag", {}).get("rules_to_suppress", [])
            ),
        ),
    )
    files["infrastructure/outputs.gen.md"] = page(
        "デプロイ出力", table(["名前", "定義"], sorted(template.get("Outputs", {}).items()))
    )
    files.update(infrastructure_docs(template, page, table))
    cases = collect_tests(ROOT)
    files["tests/unit.gen.md"] = page(
        "日本語の単体・結合テスト一覧",
        "テスト定義の名前・検証式をソースから抽出する。件数は静的な定義数であり、パラメーター展開後の実行件数・成否は品質レポートで確認する。\n\n"
        + table(
            ["実行系", "テスト", "正本", "検証式"],
            (
                (c["runner"], c["title"], source(c["file"], c["line"]), c["assertions"])
                for c in cases
            ),
        ),
    )
    return files


def input_paths():
    paths = [
        *ROOT.glob("backend/**/*.py"),
        *ROOT.glob("backend/**/*.sql"),
        *ROOT.glob("frontend/src/*.ts"),
        *ROOT.glob("frontend/src/*.tsx"),
        *ROOT.glob("frontend/e2e/*.ts"),
        *ROOT.glob("frontend/report-tests/*.ts"),
        *ROOT.glob("frontend/*.ts"),
        *ROOT.glob("tools/report_assets/*"),
        ROOT / "docs/design/DESIGN_GUIDE.manual.md",
        *ROOT.glob("infra/**/*.py"),
        *ROOT.glob("tests/*.py"),
        *ROOT.glob("tools/*.py"),
        *ROOT.glob("documentation/*.mjs"),
        *ROOT.glob("documentation/src/**/*.ts"),
        *ROOT.glob("documentation/src/**/*.astro"),
        *ROOT.glob("documentation/src/**/*.css"),
        *ROOT.glob("documentation/public/*"),
        ROOT / "documentation/package.json",
        ROOT / "documentation/package-lock.json",
        *ROOT.glob("tools/*.mjs"),
        ROOT / "frontend/package.json",
        ROOT / "frontend/src/style.css",
        ROOT / "uv.lock",
        ROOT / "frontend/package-lock.json",
        ROOT / "spec/requirements/requirements.qnt",
        ROOT / "spec/skills/skills.qnt",
        ROOT / "pyproject.toml",
        ROOT / "AGENTS.md",
        ROOT / "README.md",
        *ROOT.glob(".github/workflows/*.yml"),
    ]
    return sorted(set(p for p in paths if "__pycache__" not in p.parts))


def render():
    inputs = input_paths()
    for path in inputs:
        if path.is_symlink() or any(p.is_symlink() for p in path.parents if p.is_relative_to(ROOT)):
            raise ValueError("Symlink source refused: " + str(path))
    check_architecture()
    subprocess.run([sys.executable, "tools/generate_queries.py", "--check"], cwd=ROOT, check=True)
    _, queries = collect()
    catalog, _ = derive()
    files = database_docs(queries) | api_docs(queries, catalog) | additional_docs(catalog)
    files["queries.gen.md"] = page(
        "SQL生成カタログ",
        table(
            ["API", "SQL", "操作", "テーブル", "生成ラッパー", "SHA-256"],
            (
                (
                    q["api"],
                    source(q["source"]),
                    q["operation"],
                    q["table"],
                    source(q["generated"]),
                    q["sha256"],
                )
                for q in queries
            ),
        ),
    )
    files["manifest.gen.md"] = page(
        "生成契約・入力ハッシュ",
        "## 生成順序\n\n1. SQL AST + DDL → typed queries（別コマンドgenerate_queries.py）\n2. Quint正本 → 検証済みJSON（メモリ内）→ 要件Markdown\n3. FastAPI/OpenAPI・Python/TypeScript/SQL AST・CDK synth → 設計Markdown\n4. 再生成の一致検査 → 品質/E2E → devへMarkdownのみ自動反映 → Pages\n\n正本のコメントはDDLの日本語説明と最小限の関数概要のみ。JSON設計ファイルは保存しない。未知のDDL・文制御構造・対応不一致は生成エラーとする。図は実行証明ではなく静的構造を示し、式内の条件評価・外部呼出内部は展開しない。\n\n## 入力SHA-256\n\n"
        + table(
            ["正本", "SHA-256"],
            ((source(p), hashlib.sha256(p.read_bytes()).hexdigest()) for p in inputs),
        ),
    )
    names = sorted([*files, "README.gen.md"])
    files["README.gen.md"] = page(
        "自動生成ドキュメント",
        "`uv run python tools/design.py`で生成、`--check`で未更新・余剰ファイルを検知する。正本は実装とQuint。生成物はMarkdownのみ。\n\n"
        + table(
            ["分類", "文書"],
            (
                (name.split("/")[0], f"[{files[name].splitlines()[0].removeprefix('# ')}]({name})")
                for name in names
                if name != "README.gen.md"
            ),
        ),
    )
    return files


def publish(files, *, check=False, out=OUT):
    if any(
        not name.endswith(".md") or Path(name).is_absolute() or ".." in Path(name).parts
        for name in files
    ):
        raise ValueError("Only owned Markdown outputs are allowed")
    for path in [out, *out.rglob("*"), *(out / name for name in files)]:
        if path.is_symlink() or any(p.is_symlink() for p in path.parents):
            raise ValueError("Symlink output refused: " + str(path))
        if path.exists() and not path.is_file() and not path.is_dir():
            raise ValueError("Unsafe output: " + str(path))
    existing = {str(p.relative_to(out)) for p in out.rglob("*") if p.is_file()}
    obsolete = existing - files.keys()
    for name in obsolete:
        if BANNER.strip() not in (out / name).read_text():
            raise ValueError("Unowned output must not be removed: " + name)
    stale = [
        name
        for name, data in files.items()
        if not (out / name).is_file() or (out / name).read_text() != data
    ]
    if check and (stale or obsolete):
        raise ValueError("Generated Markdown drift: " + ", ".join(sorted(set(stale) | obsolete)))
    if not check:
        for name in stale:
            p = out / name
            p.parent.mkdir(parents=True, exist_ok=True)
            temp = p.with_suffix(".tmp")
            if temp.exists() or temp.is_symlink():
                raise ValueError("Unowned temporary output: " + str(temp))
            temp.write_text(files[name])
            temp.replace(p)
        for name in obsolete:
            (out / name).unlink()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = render()
    publish(files, check=args.check)
    print(f"Generated Markdown {'verified' if args.check else 'updated'}: {len(files)} files")


if __name__ == "__main__":
    main()
