from typing import Protocol
from uuid import UUID

from app.models import Note, NoteInput, NoteUpdate, Share


class NoteStore(Protocol):
    def list_notes(self, owner: str) -> list[Note]: ...
    def create(self, owner: str, data: NoteInput) -> Note: ...
    def get(self, owner: str, note_id: UUID) -> Note: ...
    def update(self, owner: str, note_id: UUID, data: NoteUpdate) -> Note: ...
    def delete(self, owner: str, note_id: UUID) -> None: ...
    def share(self, owner: str, note_id: UUID) -> Share: ...
    def revoke(self, owner: str, note_id: UUID) -> None: ...
    def shared(self, token: str) -> Note: ...
